### ISSUE TITLE
Allow commit messages starting with "Bug 1234 -"

### ISSUE THREAD

**Issue by oleonard** [joubu/koha-howto#2]
When I write a commit message I typically copy and paste the bug title from Bugzilla, where a hyphen is the delimiter between the bug number and the title:

Bug 18584 - Our legacy code contains trailing-spaces

I think this should be allowed by the how-to.

**Comment by joubu** [comment]
I agree with the hyphen, but what you describe is typically wrong:
The title of a bug report should describe the problem, here "Our legacy code contains trailing-spaces".
The commit message should describe what the patch does, here it "removes a trailing-space"

I'd also like to make consistent the use of "Bug 12345: " and "Bug 12345 - "

But yes I agree that the hyphen must be accepted for now.
